title: Guided Rails
email: abdullah@guidedrails.com
description: Accessibility and testing in Rails.
baseurl: ""
url: "https://guidedrails.com"

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-redirect-from
